### ISSUE TITLE
Changing usernames

### ISSUE THREAD

**Issue by shadow12490** [deargle-classes/msbx5500-spring-2020#4]
Since github actually offers user name changing functionality, I was considering changing my username to something less gamer-tag-y. It says it will break a bunch of stuff if I do that. 

I am expecting it to break my github pages stuff which should be an easy fix, but will changing my name break anything for the class repo/stuff? I don't have anything else on this account to break so class stuff is my primary concern.

**Comment by deargle** [comment]
dunno, but let me know your new tag when you change and I'll make sure you still have access to whatever

**Comment by deargle** [comment]
And keep a clone of your fork on your laptop, so that if anything breaks monumentally, you always have a backup of any work you did in there.
